- name: Create nginx folder.
  ansible.builtin.file:
    path: "{{ config_dir }}/proxy/etc-nginx/{{ item }}"
    state: directory
    mode: 0755
  become: false
  loop:
    - sites-available
    - sites-enabled
    - conf.d

- name: Copy nginx docker-compose template.
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ config_dir }}/proxy/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart nginx

- name: Install system nginx config
  become: false
  template:
    src: nginx.conf.j2
    dest: "{{ config_dir }}/proxy/etc-nginx/nginx.conf"
    mode: '0640'

- name: Install system nginx conf.d default config
  become: false
  template:
    src: conf.d-default.conf.j2
    dest: "{{ config_dir }}/proxy/etc-nginx/conf.d/default.conf"
    mode: '0640'

- name: Install system nginx mime.types
  become: false
  template:
    src: mime.types.j2
    dest: "{{ config_dir }}/proxy/etc-nginx/mime.types"
    mode: '0640'

- name: Install system nginx proxy_params
  become: false
  template:
    src: proxy_params.j2
    dest: "{{ config_dir }}/proxy/etc-nginx/proxy_params"
    mode: '0640'

- name: Install nginx proxy site config
  become: false
  template:
    src: domain.conf.j2
    dest: "{{ config_dir }}/proxy/etc-nginx/sites-available/{{ item.proxy_domain }}.conf"
    mode: '0640'
  loop: "{{ proxy_domain_names }}"

- name: Create enabled soft link for nginx site
  become: false
  file:
    src: "../sites-available/{{ item.proxy_domain }}.conf"
    dest: "{{ config_dir }}/proxy/etc-nginx/sites-enabled/{{ item.proxy_domain }}.conf"
    state: link
  loop: "{{ proxy_domain_names }}"

# - name: Reload nginx to activate specified site
#   become: yes
#   service:
#     name: nginx
#     state: restarted
    